name: Security Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Tarefa 1: SAST com Semgrep
    - name: Executar análise SAST com Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/default 
        
    # Tarefa 3: SCA com OWASP Dependency-Check
    - name: Executar análise SCA com OWASP Dependency-Check
      run: |
        mvn -B verify -DskipTests org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7