name: Pipeline Simples de Seguranca

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Obter o código do repositório
      - name: Obter o codigo
        uses: actions/checkout@v3

      # Passo 2: Dar permissão de execução ao Maven Wrapper
      - name: Dar permissao ao Maven
        run: chmod +x ./mvnw

      # Passo 3: Executar o Snyk e IGNORAR se ele encontrar erros
      - name: Executar Snyk (e ignorar erros)
        uses: snyk/actions/maven@master
        continue-on-error: true # <-- ISTO É O QUE FORÇA O SUCESSO
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # Analisa todos os projetos e reporta vulnerabilidades
          args: --all-projects