name: Pipeline de Seguranca - Sprint 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Obter o código do repositório
      - name: Obter o codigo
        uses: actions/checkout@v3

      # Passo 2: Dar permissão de execução ao Maven Wrapper
      - name: Dar permissao ao Maven
        run: chmod +x ./mvnw

      # Passo 3: Executar o Snyk
      - name: Executar Snyk para validar correcoes
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects