name: CI - Pipeline de Seguranca

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar e executar Snyk
        # A linha abaixo corrige o problema. Altere "Cybersecurity" se o nome da sua pasta for outro.
        working-directory: ./Cybersecurity
        run: |
          npm install -g snyk
          snyk test --fail-on=upgradable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
